const resData = [
    {   id : 1,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/f2727d31765309c1e5f3a0e0e3824c2e",
        restName : "Dominos",
        cuisins : "Pizza, Bhopal",
        rating : "4.2",
        price : "299",
        time : "22 minutes",
    },
    {   id : 2,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/85ccae4e3576f9330af102c46ca85395",
        restName : "Buskin Robbins",
        cuisins : "Ice Crem",
        rating : "4.3",
        price : "99",
        time : "13 minutes",
    },
    {   id : 3,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/xtjilr4hbushoxflffjm",
        restName : "Sharma & Vishnu",
        cuisins : "Veg Paneer Cheese Sandwich",
        rating : "4.1",
        price : "158",
        time : "15 minutes",
    },
    {   id : 4,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/kuisp5xx9tcutesp33yf",
        restName : "Zam Zam Fast Food",
        cuisins : "Biryani",
        rating : "3.9",
        price : "120",
        time : "32 minutes",
    },
    {   id : 5,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/46c6442ca72c545693cc2e0fcfa1aa0b",
        restName : "The Burger House",
        cuisins : "Burger",
        rating : "3.6",
        price : "79",
        time : "9 minutes",
    },
    {   id : 6,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fjguivcigogxmk3d8f7u",
        restName : "Sagar Gaire",
        cuisins : "Sandwitch",
        rating : "4.3",
        price : "2140",
        time : "11 minutes",
    },
    {   id : 7,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/d088b6ece631fd100ead7b0cdaf93047",
        restName : "Indian Coffee House",
        cuisins : "Veg Thali",
        rating : "3.9",
        price : "180",
        time : "30 minutes",
    },
    {   id : 8,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/f01666ac73626461d7455d9c24005cd4",
        restName : "KFC",
        cuisins : "Chilli Chicken",
        rating : "4.2",
        price : "220",
        time : "17 minutes",
    },
    {   id : 9,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/f2727d31765309c1e5f3a0e0e3824c2e",
        restName : "Dominos",
        cuisins : "Pizza, Bhopal",
        rating : "4.2",
        price : "299",
        time : "22 minutes",
    },
    {   id : 10,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/85ccae4e3576f9330af102c46ca85395",
        restName : "Buskin Robbins",
        cuisins : "Ice Crem",
        rating : "4.3",
        price : "99",
        time : "13 minutes",
    },
    {   id : 11,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/xtjilr4hbushoxflffjm",
        restName : "Sharma & Vishnu",
        cuisins : "Veg Paneer Cheese Sandwich",
        rating : "4.1",
        price : "158",
        time : "15 minutes",
    },
    {   id : 12,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/kuisp5xx9tcutesp33yf",
        restName : "Zam Zam Fast Food",
        cuisins : "Biryani",
        rating : "3.9",
        price : "120",
        time : "32 minutes",
    },
    {   id : 13,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/46c6442ca72c545693cc2e0fcfa1aa0b",
        restName : "The Burger House",
        cuisins : "Burger",
        rating : "3.6",
        price : "79",
        time : "9 minutes",
    },
    {   id : 14,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fjguivcigogxmk3d8f7u",
        restName : "Sagar Gaire",
        cuisins : "Sandwitch",
        rating : "4.3",
        price : "2140",
        time : "11 minutes",
    },
    {   id : 15,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/d088b6ece631fd100ead7b0cdaf93047",
        restName : "Indian Coffee House",
        cuisins : "Veg Thali",
        rating : "3.9",
        price : "180",
        time : "30 minutes",
    },
    {   id : 16,
        imgURL : "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/f01666ac73626461d7455d9c24005cd4",
        restName : "KFC",
        cuisins : "Chilli Chicken",
        rating : "4.2",
        price : "220",
        time : "17 minutes",
    },


];

export default resData;